import { ProjectCard } from "./ProjectCard";
import { Reveal } from "./Reveal";

const projects = [
  {index:"01",title:"Cardápio Digital",variant:"menu" as const,description:"Aplicação de cardápio digital para lanchonetes, criada com foco em experiência mobile, personalização de pedidos e fechamento direto pelo WhatsApp.",highlights:["Categorias, produtos, adicionais, combos e carrinho de compras","Fluxo de entrega ou retirada, pagamento e revisão do pedido","Área administrativa com Supabase, autenticação, banco de dados e RLS"],tags:["Vite","React","TypeScript","Tailwind CSS","Supabase","Zod","WhatsApp"],githubUrl:"https://github.com/LEBEATO/cardapio-digital",liveUrl:"https://github.com/LEBEATO/cardapio-digital"},
  {index:"02",title:"FrotaPro",variant:"fleet" as const,description:"Plataforma de gestão de frotas criada para operações com múltiplos estados e bases, conectando gestores, unidades e motoristas.",highlights:["Acesso por papéis e segregação de dados por unidade","Checklist diário, combustível e manutenção","Supabase Auth, banco Postgres e políticas RLS"],tags:["Next.js","TypeScript","Supabase","PostgreSQL","Tailwind CSS"],githubUrl:"https://github.com/LEBEATO/frotapro",liveUrl:"https://frotapro-zeta.vercel.app"},
  {index:"03",title:"Prova-IA",variant:"ai" as const,description:"Plataforma de estudos e simulados por banca e cargo, combinando autenticação, banco de dados e recursos de inteligência artificial.",highlights:["Simulados organizados por edital, banca e cargo","Integração de IA para apoiar questões e revisão","Supabase Auth, banco de dados, Storage e RLS"],tags:["Next.js","TypeScript","Supabase","Inteligência Artificial","RLS"],githubUrl:"https://github.com/LEBEATO/prova-ia",liveUrl:"https://prova-ia-six.vercel.app"},
  {index:"04",title:"Loja Pets",variant:"pets" as const,description:"E-commerce responsivo para o mercado pet com catálogo visual e experiência focada em conversão.",highlights:["Interface moderna e totalmente adaptada para celular","Experiência de compra organizada e intuitiva","Componentes reutilizáveis e microinterações"],tags:["Next.js","React","TypeScript","Tailwind CSS"],githubUrl:"https://github.com/LEBEATO/lojapets",liveUrl:"https://lojapets-coral.vercel.app"},
  {index:"05",title:"Fortinat Shop",variant:"shop" as const,description:"Aplicação de e-commerce integrada a API externa, preparada para compras, histórico e coleção do usuário.",highlights:["Catálogo consumido de API externa","Persistência com Prisma e PostgreSQL","Filtros, autenticação e experiência de compra"],tags:["Next.js","Prisma","PostgreSQL","API REST","TypeScript"],githubUrl:"https://github.com/LEBEATO/fortinate-shopp",liveUrl:"https://fortinate-shopp.vercel.app"},
];

export function Projects(){return <section id="projetos" className="section-space relative"><div className="absolute inset-x-0 top-0 h-px bg-gradient-to-r from-transparent via-white/10 to-transparent"/><div className="container-shell"><Reveal><span className="eyebrow">Trabalhos selecionados</span><div className="mt-3 flex flex-col justify-between gap-5 md:flex-row md:items-end"><h2 className="section-title max-w-2xl">Projetos que resolvem <span className="gradient-text">problemas reais.</span></h2><p className="max-w-md leading-7 text-white/50">Produtos completos que demonstram interface, regras de negócio, integração, IA e banco de dados.</p></div></Reveal><div className="mt-14 grid gap-7">{projects.map(project=><ProjectCard key={project.title} {...project}/>)}</div></div></section>}